{
 "title": "Experiment",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "avg",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_sum/http_server_requests_seconds_count"
    }
   ]
  },
  {
   "title": "sum(count_over_time({job=\"monitoring-demo\"}[30m])) by (level)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"monitoring-demo\"}[30m])) by (level)"
    }
   ]
  },
  {
   "title": "{job=\"monitoring-demo\",level=\"INFO\"}",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{job=\"monitoring-demo\",level=\"INFO\"}"
    }
   ]
  },
  {
   "title": "http_server_requests_seconds_count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_count"
    }
   ]
  }
 ]
}